language: java
branches:
  only:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
    - LuisMiguel.Ortiz.Rozalen@alumnos.upm.es
script:
#Test unitario y de integracion en perfil DEV, con cobertura
- mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=luismoteando -Dsonar.login=$SONAR
#Deploy https://zest-workout-planner-backend.herokuapp.com/api/v0/api-info
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master